<a href="https://colab.research.google.com/github/govardanalowkya/neural-/blob/main/nndl_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Create two {2,3} tensors with random values
A = np.random.rand(2, 3)
B = np.random.rand(2, 3)
# Element-wise addition
C = A + B
print("Tensor A:\n", A)
print("Tensor B:\n", B)
print("A + B:\n", C)


Tensor A:
 [[0.74457843 0.34351094 0.73868139]
 [0.23364187 0.56378537 0.2617155 ]]
Tensor B:
 [[0.3149467  0.45675269 0.95147625]
 [0.29217617 0.73066196 0.83607915]]
A + B:
 [[1.05952513 0.80026363 1.69015764]
 [0.52581804 1.29444733 1.09779465]]


In [ ]:
import tensorflow as tf

def main():
    # Create two {2,3} tensors with random values
    tensor_a = tf.random.uniform(shape=(2, 3), minval=0.0, maxval=1.0)
    tensor_b = tf.random.uniform(shape=(2, 3), minval=0.0, maxval=1.0)

    # Element-wise addition
    result = tf.add(tensor_a, tensor_b)

    # Print tensors
    print("Tensor A:")
    print(tensor_a.numpy())

    print("\nTensor B:")
    print(tensor_b.numpy())

    print("\nElement-wise Addition (A + B):")
    print(result.numpy())

if __name__ == "__main__":
    main()


Tensor A:
[[0.7407843  0.3879447  0.00362182]
 [0.22624207 0.28336263 0.51108265]]

Tensor B:
[[0.38633144 0.05366623 0.13551629]
 [0.36370277 0.43999434 0.94987833]]

Element-wise Addition (A + B):
[[1.1271157  0.44161093 0.1391381 ]
 [0.58994484 0.72335696 1.460961  ]]


In [ ]:
import random

def main():
    # Create two {2,3} tensors (lists of lists) with random values
    tensor_a = [[random.random() for _ in range(3)] for _ in range(2)]
    tensor_b = [[random.random() for _ in range(3)] for _ in range(2)]

    # Element-wise addition
    result = [
        [tensor_a[i][j] + tensor_b[i][j] for j in range(3)]
        for i in range(2)
    ]

    # Print results
    print("Tensor A:")
    for row in tensor_a:
        print(row)

    print("\nTensor B:")
    for row in tensor_b:
        print(row)

    print("\nElement-wise Addition (A + B):")
    for row in result:
        print(row)

if __name__ == "__main__":
    main()


Tensor A:
[0.43787685261885245, 0.8274806860587073, 0.14689624658712808]
[0.33568203795596574, 0.2578187186473897, 0.7838818957361685]

Tensor B:
[0.34213976915805033, 0.9732446403290715, 0.6045727805456167]
[0.5885990892478076, 0.9132007756694428, 0.7148138885741735]

Element-wise Addition (A + B):
[0.7800166217769028, 1.800725326387779, 0.7514690271327448]
[0.9242811272037733, 1.1710194943168326, 1.4986957843103421]


In [ ]:
import tensorflow as tf
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>